### ISSUE TITLE
List of Questions

### ISSUE THREAD

**Issue by abieber1408** [abieber1408/capstone-project#1]
## Value proposition

As an user
I want  to list a question and two possible answers
So that I can read the question and choose one answer and see the result.

## Description

- Scribble / design or text
- Precise, no unnecessary information

## Acceptance criteria

-The  Question should appear on the top.
-Boths answer should appear on the card.
-After clicked on answer  it should appear the "richtig!!" or the "falsch!!" text on the card.

## Tasks

- [x] Create database with Questions and answers.
- [x] Add to App.
- [x] Create Card with two buttons.

![Image](https://user-images.githubusercontent.com/110246640/229295292-51a5dc1b-5260-45ed-866d-aeb5d051bf5e.png)

**Comment by liebeckm** [comment]
nice! ☺️ 
my suggestions:
- add the image below the description heading and delete the existing placeholder text
- navbar is not necessary for the moment because the links do not work yet
- task "create card component" is missing
- there is no answer button to click on screen 1
- screen 2 needs a "next question" button maybe?

**Comment by LuYujin9** [comment]
here are my suggestions :

- the Scribble should be under the Description.
- for answers , they should be "input", type is "radius", not "checkbox",
- add a button for answer submit, then people can change their answer before they decide.

**Comment by PReichetanz** [comment]
Hi Anita,

a really good start for your user story! 🎉

I would only like to add one thing in order to simplify your story:

Please consider to show the "richtig" or "falsch" on the same screen as the question for now, because I don't think it's necessary to create a different page for that. If you will need another page for this, you can add it in another user story.

**Comment by salaos** [comment]
Hi! I still agree with the opinions above:

- picture with the scribble should be under the headline "description"
- button for answer submit would be helpful
- task "create card component" is missing
- if "richtig" or "falsch" appears, there should be another button "next question" - or maybe the code planned for automatically showing the next question
