### ISSUE TITLE
Start Form-updated

### ISSUE THREAD

**Issue by abieber1408** [abieber1408/capstone-project#15]
## Value proposition

As an user
I want see the start page of the app with different sections
to be able to introduce name, topic, level, a video screen and a button that links to questions.

## Description

- Scribble / design or text
- Precise, no unnecessary information

## Acceptance criteria

- [x] Logo of the App should Appear at the top.
- [x] See input field for name . Should enter name.
- [x] Should have a screen for video.
- [x] See input field for Topic  with option value 'topic': - topics, to select.
- [x] See input field for Level with option value 'level' : to select levels 1, 2, 3 or 4.
- [x] See image about Topic, should appear after choose topic.
- [x] Button for continue with the quiz question.

## Tasks

- [x] Create a Form
- [x] Add input labels for name, topic and level.
- [x] Link to library.
- [x] Local storage
- [x] Link with QuestionButton  Card. 
- [x] Add Button to link with Question Card.

![Unbenannt-2023-04-22-0913](https://user-images.githubusercontent.com/110246640/233769532-1af3877e-d3e4-4ee7-b5eb-07bb493fd523.svg)

**Comment by PReichetanz** [comment]
Hi Anita,

just a few thoughts:
- When is the video displayed? if I click start? This should be written down in the Acceptance Criteria.
- What happens if I click start without entering a name of a level nor a topic? => AC
- What is the white circle next to the name input field?
- If the video depends on the chosen topic: what is displayed before I choose a topic?
- As soon as the video is finished, how do I go to the next page (and how does this page look like)?

Please add these information to the ACs and the description. Additionally, please put the scribble under the Description heading.

**Comment by abieber1408** [comment]
Thank you for your comments.
I change layout and add buttons and put more specification.
I hope this works.

**Comment by PReichetanz** [comment]
Hi @abieber1408,
this is really good!

Because this is a big one, I still suggest to move the video part to another user story so that you can focus on the name, topic, and level first and then start the quiz directly.
In the next story, you add the video.

But this decision is now up to you.

**Comment by abieber1408** [comment]
Thank You for looking.  There is another User story I put on slack yesterday, US5 for these purpose.
I will change some Tasks on it and publish it again later.

**Comment by liebeckm** [comment]
looks good! :)
