### ISSUE TITLE
Video Streaming.

### ISSUE THREAD

**Issue by abieber1408** [abieber1408/capstone-project#16]
## Value proposition

As an user
I want  to see the video I chose
to be able watch and hear about the topic and go to the question for the quiz.

## Description

- Scribble / design or text
- Precise, no unnecessary information

## Acceptance criteria

- [x] The video must be short.
- [x] I must hear and see the video.

## Tasks

- [x] Link topic with video.
- [x] Stream video.

![Image](https://user-images.githubusercontent.com/110246640/233770931-de211eb9-ac54-4da1-a3e3-38a7af66a3ef.svg)

**Comment by PReichetanz** [comment]
I think you need to combine this story with #15 because #15 does not make any value to the user without the things you describe here.

Consider to move the video to another user story (playing videos is complicated enough to outsource it).

**Comment by liebeckm** [comment]
Hey Anita, nice! I was just wondering where you take that video from? depending on that, it would be good to explain here how you'd like to implement it into your app :)

**Comment by abieber1408** [comment]
Thank you for the suggestion. I'm working on that.

**Comment by Satttoshi** [comment]
LGTM, be careful, proper Videoplayers might be tricky, good luck
