### ISSUE TITLE
Scores and level view.

### ISSUE THREAD

**Issue by abieber1408** [abieber1408/capstone-project#7]
## Value Proposition

**As a** ...      user  
**I want to**      I want to see the level, score and correct answer
**so that** I can see the results of my game.
​

## Description

Design / Text / Scribble
​

## Acceptance Criteria

- [x] Level, StarScore and answered question/total questions are visible on the right.
- [x] The label Level has to by above.
- [x] A star for score must appears.
      ​
## Tasks

- [x] Create Counters
- [x] Add Styling

![Image](https://user-images.githubusercontent.com/110246640/229473887-6985cd81-19ef-423d-872a-aaabdb3f49a5.svg)

**Comment by augustinanders** [comment]
LGTM!
