### ISSUE TITLE
Question Buttons

### ISSUE THREAD

**Issue by abieber1408** [abieber1408/capstone-project#8]
## Value Proposition

**As a** .user
**I want to** I want to see all the buttons for the questions in my game App
**so that**I can choose the start-button and the question buttons.
​

## Description

 Design / Text / Scribble
​

## Acceptance Criteria

- [x] Question and star button must be aligned in a Grid.
- [x] The answers should be buttons.
- [x] After clicked on a button it has to be linked with the QuestionAnswerCard
      ​

## Tasks

- [x] Create Question-Button Card.
- [x] Add and create the buttons.
- [x] Link to Card.

![Image](https://user-images.githubusercontent.com/110246640/229475624-89323d68-5a2c-4d0a-8a48-4a2bf54f484e.svg)

**Comment by augustinanders** [comment]
i do not really understand the concept here. be more precise. I dont get what the different button types are for?

**Comment by abieber1408** [comment]
Every button is a step forward to go to the end. At the end you become an Image and the challenge is complete.
