### ISSUE TITLE
Image and Subject-Name of my questions.

### ISSUE THREAD

**Issue by abieber1408** [abieber1408/capstone-project#9]
## Value Proposition

**As a**user
**I want to** I want to see and Image and the name of the subject I choose
**so that**I can know the subject it is.
​

## Description

Design / Text / Scribble

## Acceptance Criteria

- [x] Subject name must appear above the image.
- [x] Image must appear aligned. 

## Tasks

- [x] Add Image.
- [x] Create name Label

![Image](https://user-images.githubusercontent.com/110246640/229477930-724fc477-8f8b-443a-a937-a01912d82078.svg)
